server:
  port: ${SERVER_PORT:8082}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://34.68.101.6:3306/payment
    username: craft
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: refresh, health